### ISSUE TITLE
Groovy -- bump up to 1.0

### ISSUE THREAD

**Issue by jd327** [hashids/hashids.github.io#14]
Hey Chad,

I updated the site (http://hashids.org/) + my versions. Here's what's different: https://github.com/ivanakimov/hashids.js#changelog (which is not much).

Also, I got rid of www on the site (it was hosted on S3 before and it was required there when I started), but now it's on Github so it's cleaner without it. Redirects still work tho (www -> non).

Good job following up with that Grails plugin btw, as soon as I saw it on Twitter, I added it to the list @ http://hashids.org/groovy/

If you have any issues with the site (https://github.com/hashids/hashids.github.io/issues/4) or any issues in general, just ping :]

**Comment by 4kimov** [comment]
Closing since [the project is moving](https://github.com/hashids). @cmaron if you feel like helping out with Groovy for the new algorithm, please let me know so I can add you as maintainer.
