### ISSUE TITLE
Negative integers not supported?

### ISSUE THREAD

**Issue by anentropic** [hashids/hashids.github.io#21]
I tried to encode a negative integer with the Python version and get an empty string back.

I assume for the intended use case (database primary key ids) this doesn't matter but maybe you could mention it on the homepage somewhere - I didn't see any reference to only positive ints being supported.

**Comment by ivanakimov** [comment]
Good point, thank you for bringing it up. Update the site to mention positive integers in 2 places:

1. [Features](http://hashids.org/python/#features)
2. [What not to do](http://hashids.org/python/#what-not-to-do)
