### ISSUE TITLE
For big numbers nothing is returned

### ISSUE THREAD

**Issue by Showvhick** [hashids/hashids.github.io#22]
First of all, thanks for making such a wonderful package for generating hash code, but I am experiencing an issue. When the input number is more than 200 crore ( say 3232323213 ), No data is getting returned. I am not so sure about the number where it's breaking. but it's more than 200 crore I am sure. Please look into this issue. Thanks

**Comment by ivanakimov** [comment]
Which library are you using?

**Comment by Showvhick** [comment]
Sorry for late reply. I am using php library.Thanks

On Wed, Apr 22, 2015 at 10:36 PM, Ivan Akimov <notifications@github.com>
wrote:

> Which library are you using?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/hashids/hashids.github.io/issues/22#issuecomment-95265997>
> .
>



-- 
Showvhick Nath
Kolkata,India
Mob: +919593471486
Alt.email- showvhick@live.com
twitter-@showvhick

**Comment by ivanakimov** [comment]
Did you read the [big numbers](https://github.com/ivanakimov/hashids.php#big-numbers) section?

**Comment by Showvhick** [comment]
Oh ok. Sorry I didn't see it. Okay I understand. Thanks

On Fri, Apr 24, 2015 at 3:43 AM, Ivan Akimov <notifications@github.com>
wrote:

> Did you read the big numbers
> <https://github.com/ivanakimov/hashids.php#big-numbers> section?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/hashids/hashids.github.io/issues/22#issuecomment-95733116>
> .
>



-- 
Showvhick Nath
Kolkata,India
Mob: +919593471486
Alt.email- showvhick@live.com
twitter-@showvhick
