### ISSUE TITLE
How exact is hashid?

### ISSUE THREAD

**Issue by smolinari** [hashids/hashids.github.io#24]
Playing with the demo, I found this.

![image](https://cloud.githubusercontent.com/assets/3314957/11141918/d4abf9f8-89e9-11e5-928d-b2d5238b137c.png)

Is this normal?

Scott

**Comment by ivanakimov** [comment]
Hi Scott,

It's just overflowing. For JavaScript libs, I wouldn't go higher than 9007199254740991 (see [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)).

**Comment by smolinari** [comment]
Yeah, sorry. I did some more reading and realized the number was probably too big. 

Btw, I love the library. It is a perfect fit to make the RIDs of OrientDB, which are two integers, opaque, for Node Ids in graphQL queries.  

Scott

**Comment by ivanakimov** [comment]
Cool, glad you find it useful :)
