### ISSUE TITLE
Haxe implementation

### ISSUE THREAD

**Issue by kevinresol** [hashids/hashids.github.io#30]
Hi there, 

I have recently ported the implementation hashids to the [Haxe](http://haxe.org) language which can be found [here](https://travis-ci.org/kevinresol/hashids). It would be my pleasure to get it listed in the website.

Thanks.
Kevin

**Comment by ivanakimov** [comment]
Hi Kevin, this is great! I'll be sure to add it this weekend :) In the meantime, can you send me a quick email at ivan@barreleye.com in case I run into any questions/issues.

**Comment by ivanakimov** [comment]
http://hashids.org/haxe/
