### ISSUE TITLE
Lua implementation

### ISSUE THREAD

**Issue by un-def** [hashids/hashids.github.io#33]
Hi there,

I'm maintainer of a [hashids.lua fork](https://github.com/un-def/hashids.lua). The hashids.org site now refers to [original version of hashids.lua by leihog](https://github.com/leihog/hashids.lua) that is not compiled with Lua version > 5.1, has a few bugs and seems abandoned by author (I have tried to contact leihog via GitHub PR and email without success).

Is it possible to add/replace the Lua implementation link to my fork repo?

**Comment by ivanakimov** [comment]
Hi @un-def,

Thanks for the update. Have you tried submitting PRs with your bug fixes (not just contacting the author)? This might shine more light on the actual issues & encourage discussion. It looks like there's currently [zero issues](https://github.com/leihog/hashids.lua/issues) and [no PRs](https://github.com/leihog/hashids.lua/pulls) for that repo.

If you don't get a response to those within a reasonable time, I'll ping Leif and we can see how to go about it. Thanks for taking the time to look at the original code.

cc @leihog

**Comment by un-def** [comment]
There is closed (by me) PR — https://github.com/leihog/hashids.lua/pull/1
I can open an issue if you think it will help to contact the author.

**Comment by ivanakimov** [comment]
Ah, I see. Yeah, it looks like it wasn't open for very long. I think you should re-open whatever PRs you have and give @leihog a bit more time to reply.

**Comment by un-def** [comment]
OK, I create another PR — https://github.com/leihog/hashids.lua/pull/2

**Comment by ivanakimov** [comment]
Thank you @un-def.

**Comment by leihog** [comment]
@ivanakimov thanks for pinging me. 
@un-def your mails are being classified as spam, I think google blocks all mails from yandex.ru which is why I didn't get your email. We'll continue the conversation on the PR itself.

**Comment by ivanakimov** [comment]
Cool. Looks like you guys have a conversation going, so I'll close this issue.
