### ISSUE TITLE
Hashids specification

### ISSUE THREAD

**Issue by matthewvalimaki** [hashids/hashids.github.io#36]
The following opinion is based on my report for Go version of Hashids, see https://github.com/speps/go-hashids/issues/28.

I propose Hashids to implement an API of sorts so that all implementations mentioned on the website expose same methods, so that functionality is close to 1:1 with all libraries and furthermore unconventionally I propose the Hashids also to list minimum unit tests to implement.

Reasoning:

1. https://github.com/ivanakimov/hashids.js supports `encodeHex` and `decodeHex` and https://github.com/speps/go-hashids does not. So I am left to wonder if it should implement those or not. I understand that libraries should be able to do what they want but it would benefit to know what are the minimums. I am not absolutely sure whether strict interface could be enforced due to language differences. For example in JS `encode()` accepts strings, integers and arrays while in Go only int slice (`[]int`) is accepted. I like strictness but it could hinder language specific strengths.

2. With minimum unit tests defined we should be fairly confident that operation across libraries is the same.

**Comment by 4kimov** [comment]
Closing since [the project is moving](https://github.com/hashids). New algorithm is going by the new spec: https://github.com/sqids/sqids-spec
