### ISSUE TITLE
Live hashids demo

### ISSUE THREAD

**Issue by glenndevenish** [hashids/hashids.github.io#39]
Not an issue, but there's a live version of the [hashids link on your website](http://codepen.io/ivanakimov/pen/bNmExm) here:
> https://codepen.io/glenndevenish/pen/EwYjbJ

Feel free to link or copy it or whatever 😸

**Comment by 4kimov** [comment]
Closing since [the project is moving](https://github.com/hashids). New website has a working demo now.
