### ISSUE TITLE
Kotlin version is worse than useless

### ISSUE THREAD

**Issue by CorayThan** [hashids/hashids.github.io#41]
The Kotlin version is worse than useless. Looks like it was probably converted from Java a long time ago, before Kotlin reached 1.0, so it has many many compilation issues.

Anyone using this in Kotlin would be better off using the Java version. I would recommend removing the Kotlin one. Being published on Maven as a library is another big benefit of the Java version.

It looks like this ticket:

https://github.com/leprosus/kotlin-hashids/issues/2

Is an attempt to whole sale fix the many many issues it has, so if you don't want to remove the Kotlin version it at least needs to be fixed.

**Comment by 4kimov** [comment]
Closing since [the project is moving](https://github.com/hashids). @CorayThan let me know if you'd like to help out with https://sqids.org/kotlin
