### ISSUE TITLE
Why list?

### ISSUE THREAD

**Issue by sporto** [hashids/hashids.github.io#42]
Hi, I would like to know why encode and decode using arrays. 

Main use case for this spec seems to be hashing individual resource ids. E.g. you want `/users/1Aq`
In most case you will deal with one id. I'm wrong thinking this? (at least for I want to use this)

Using list make things cumbersome as I need to grab the first item in the list and add error handling to that. Specially in more strict languages like Haskell, Rust, etc.

If I want to encode or decoder several ids is not difficult to something like `map`. e.g.

```
// Elm
map encode [1,2,3]

// JS
[1,2,3].map(hashids.encode)
```

Maybe encoding/decoding all in one is substantially faster? 
Thanks

**Comment by ivanakimov** [comment]
Arrays were introduced to give more flexibility -- one id can be decoded to represent several things (`123` community, `456` user id, `789` product id).

In JavaScript, you can use arrays as well as numbers:
```javascript
hashids.encode(1);
hashids.encode([1]);
```

If one of the Hashids ports does not support both numbers and arrays (and it's not a language limitation), then feel free to open an issue or a PR.

**Comment by sporto** [comment]
Rust implementation only returns a list on decode. 
Is that the spec? To only return a list?

**Comment by kevinresol** [comment]
@sporto The hashids algorithm encodes/decode list(array) of number.
If you want to encode only one number, then put only one number in the list.
