### ISSUE TITLE
Comparing hashids for sorting?

### ISSUE THREAD

**Issue by phaddius** [hashids/hashids.github.io#43]
This may be a dumb question, but can hashids be sorted and compared alphanumerically?

If x < y, is hashid(x) < hashid(y) alphanumerically?

This would be useful to know in order to sort a list of objects based on their creation order using only their hashids.

**Comment by kevinresol** [comment]
I think you can answer yourself with a simple experiment similar to this:

With salt = "a":

1 => RD 
2 => 6P
3 => aE

**Comment by 4kimov** [comment]
Closing since [the project is moving](https://github.com/hashids).
