### ISSUE TITLE
Update link for Symfony

### ISSUE THREAD

**Issue by roukmoute** [hashids/hashids.github.io#44]
Hi!

I would like to know if you accept to update the link of bundle.
I have my own bundle which was updated frequently and I prepare a new version.
And it was already added in https://symfony.sh/

Here it is: https://github.com/roukmoute/HashidsBundle

What do you think?

**Comment by 4kimov** [comment]
@roukmoute Sorry for the super late response. Thanks for the bundle, if you'd like to help out with https://sqids.org/php, please let me know.

Closing since [the project is moving](https://github.com/hashids).
