### ISSUE TITLE
hash collision

### ISSUE THREAD

**Issue by arianne-detorres** [hashids/hashids.github.io#48]
Hi, I'm using hashids to encode internal ids in our system, however I noticed a few collisions: 

```
Hashids hashids = new Hashids( salt, 8, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890" );
System.out.println(hashids.encode( 5551008 ));
System.out.println(hashids.encode( 5552196 ));
```

Returns:
```
mnbgLzGm
mnbgLZGm
```

Any ideas as to how this can happen? From the documentation, it seems this should be impossible.  We're using the latest version (1.0.3)

**Comment by miquelfire** [comment]
You'll need to post in the library of the language you're using. There might be a bug with that language's implentation.

**Comment by jd327** [comment]
Generated ids are case-sensitive by default. As you can see in your example, the "z" is different.
