### ISSUE TITLE
Decrypting Hash key

### ISSUE THREAD

**Issue by Bruskyer** [hashids/hashids.github.io#51]
hello, I have tried to make my  long url to shorten with this useful library but I have a issue about decrypting hashing data?
please can you share any sample or information regarding issue?
Regards
Thanks

**Comment by niieani** [comment]
Please share the example that caused the issue you describe, otherwise we cannot tell you what was wrong.

**Comment by 4kimov** [comment]
Closing since [the project is moving](https://github.com/hashids).
