### ISSUE TITLE
Rust implementation is unmaintained 

### ISSUE THREAD

**Issue by leocavalcante** [hashids/hashids.github.io#53]
[Rust version](https://hashids.org/rust/) points to https://github.com/charsyam/hashids_rust, but the project "seams" to be unmaintained for about 4 years: https://github.com/charsyam/hashids_rust/issues/2

An alternative might be: https://github.com/archer884/harsh

**Comment by AdriaanPrinsloo** [comment]
This is even more of a problem than being unmaintained, referencing it in a project causes dependency errors.

**Comment by 4kimov** [comment]
Closing since [the project is moving](https://github.com/hashids).

`harsh` is referenced here: https://sqids.org/rust
