### ISSUE TITLE
JavaScript page needs more docs

### ISSUE THREAD

**Issue by SamJarmanPP** [hashids/hashids.github.io#58]
Hi Team,

The JavaScript page (https://hashids.org/javascript/) has a fair amount of documentation missing that is available on its read me - example: around padding of hash ids (for greater length). 

Happy to open a PR - but if anyone else wants to do get in there I'm happy for that too. 

If I were to open a PR - are there some standards that each language page should mention / not mention?

**Comment by 4kimov** [comment]
@SamJarmanPP Sorry for the super late response. Docs are more detailed in the individual repo READMEs, website is more of an intro.

Closing since [the project is moving](https://github.com/hashids).
