### ISSUE TITLE
Add Postgres pure SQL solution

### ISSUE THREAD

**Issue by braco** [hashids/hashids.github.io#59]
This should be added [to the documentation](https://github.com/hashids/hashids.github.io/issues/59#issue-627885799) IMO, I found it necessary in AWS RDS and was lucky to see it mentioned somewhere:

https://github.com/andreystepanov/hashids.sql

**Comment by 4kimov** [comment]
@braco Thanks for the heads up and sorry for the super late reply. Closing since [the project is moving](https://github.com/hashids).

@andreystepanov Please let me know if you'd like to help out with https://sqids.org/plpgsql, I'd be happy to add you as a maintainer.
