### ISSUE TITLE
Demo on Codepen is broken

### ISSUE THREAD

**Issue by kohlerdominik** [hashids/hashids.github.io#61]
The `check out the demo` on codepen is currently broken.

> ReferenceError: Hashids is not defined

I guess there should be some reference defined to the source, which is not there anymore.

BTW: The example from #39 is maybe even better than the current one?

**Comment by callumgare** [comment]
Looks like the codepen needs to have the hashids and jQuery libraries added to the external scripts settings of that pen. Once I added https://cdnjs.cloudflare.com/ajax/libs/hashids/2.2.10/hashids.min.js and https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js it worked for me. @niieani you look like you were modify the website, are you able to update this or ping whoever would be able to? Ta :)
![image](https://user-images.githubusercontent.com/346340/184524514-d49f9ce8-8d21-4a98-bc95-aecff33d912b.png)

**Comment by 4kimov** [comment]
Thanks for the heads up and sorry - that's my bad for letting it become outdated.

Closing since [the project is moving](https://github.com/hashids). The new website has a working demo/playground @ https://sqids.org/ (scroll to the bottom)
