### ISSUE TITLE
Python -- bump up to 1.0

### ISSUE THREAD

**Issue by ivanakimov** [hashids/hashids.github.io#7]
Hey David,

I updated the site (http://hashids.org/) + my versions. Here's what's different: https://github.com/ivanakimov/hashids.js#changelog (which is not much).

Also, I got rid of www on the site (it was hosted on S3 before and it was required there when I started), but now it's on Github so it's cleaner without it. Redirects still work tho (www -> non).

If you have any issues with the site (https://github.com/hashids/hashids.github.io/issues/4) or any issues in general, just ping :]

**Comment by davidaurelio** [comment]
Implemented in davidaurelio/hashids-python@3118483d71e604315619789c540c458fb18afbd1

I will take care of the site later

**Comment by ivanakimov** [comment]
Awesome. No worries, I got the site.

**Comment by davidaurelio** [comment]
Thank you, great!

To my embarrassment I have to admit that I assumed that the encoding algorithm would have changed, and therefore deferred the work. Yesterday, I was looking at the diff of v0.3 and 1.0 of the JS implementation and felt bad.

**Comment by ivanakimov** [comment]
Hah. That's funny. On the other hand, must've been a nice surprise!

**Comment by davidaurelio** [comment]
Absolutely :)
