### ISSUE TITLE
Hello everybody, I've wrote a new Java library which is compatible with the latest "niieani/hashids.js" version

### ISSUE THREAD

**Issue by 1s1y** [hashids/hashids.github.io#87]
The project is https://github.com/yatracker/hashids

- Number large than the safe number and BigInteger support
- Complex unicode characters support, emojis
- Some performance improve

I hope my project can be added to the website 🥰

**Comment by 4kimov** [comment]
@1s1y Sorry for the late response, please let me know if you'd like to port your version to https://sqids.org/java and I can add you as a maintainer.

Closing since [the project is moving](https://github.com/hashids).
