### ISSUE TITLE
Objective-C -- bump up to 1.0

### ISSUE THREAD

**Issue by jd327** [hashids/hashids.github.io#9]
Hey Jofell,

I updated the site (http://hashids.org/) + my versions. Here's what's different: https://github.com/ivanakimov/hashids.js#changelog.

Looks like Obj-C version is still at ~0.1.4, which differs a bit more from 0.3. Are you up for the update?

Also, I got rid of www on the site (it was hosted on S3 before and it was required there when I started), but now it's on Github so it's cleaner without it. Redirects still work tho (www -> non).

If you have any issues with the site (https://github.com/hashids/hashids.github.io/issues/4) or any issues in general, just ping :]

**Comment by 4kimov** [comment]
Closing since [the project is moving](https://github.com/hashids). @jofell if you feel like helping out with https://sqids.org/objective-c, please let me know so I can add you as maintainer.
